package com.greact.model;

/**
 * Special!
 *
 * @param <T> dangling, but will be checked by JScripter
 * @param <V> type of field value
 */
public interface MemberRef<T, V> {
    default String[] memberNames() {throw new RuntimeException("must be autogenerated");}
    default String className() {throw new RuntimeException("must be autogenerated");}
    V value(T t);
}