/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java`
}

repositories {
    jcenter()
    mavenLocal()
    //maven(url = "http://repository.jsweet.org/artifactory/libs-release-local")
    //maven(url = "http://repository.jsweet.org/artifactory/libs-snapshot-local")
}

dependencies {
    implementation("org.jsweet:jsweet-core:6.2.0")
    implementation("com.over64:jscripter:0.0.1")
    implementation("com.over64:jscripter-transpiler:0.0.1")
}

java {
    sourceCompatibility = JavaVersion.VERSION_14
}

tasks.withType<JavaCompile> {
    options.compilerArgs.add("--enable-preview")
    options.compilerArgs.add("-Xplugin:jScripter --js-src-package=greact.sample.plainjs")
    options.fork()
    options.forkOptions.jvmArgs = listOf("--enable-preview")
}