package greact.sample.plainjs.demo;

import com.over64.greact.dom.HTMLNativeElements.*;
import greact.sample.plainjs.demo.searchbox.SearchBox;
import greact.sample.plainjs.demo.searchbox.StrInput;

import static greact.sample.SuperDemo.Server.server;

public class UsersPage implements Component0<body> {
    record User(long id, String name, int age, String sex) {}
    record UserInfo(String faculty, String address, String phone) {}

    /**
     * @param <T> dangling, but will be checked by JScripter
     * @param <V> type of field value
     */
    interface MemberRef<T, V> {
        default String memberName() {return "must be autogenerated";}

        V value();
    }

//    String nameLike = "";
//    User[] users = new User[]{};

    @Override
    public body mount() {
//        User u = new User(0, "", 42, "male");
//        MemberRef<User, Long> mref = u::id;
        return new body() {{
//            new input() {{
//                style.maxWidth = "300px";
//                placeholder = "Имя студента...";
//                onchange = ev -> nameLike = ev.target.value;
//            }};
//            new button("искать") {{
//                onclick = ev -> effect(users = server(db -> db.array(
//                    "SELECT * FROM users WHERE name like :1",
//                    User.class, "%" + nameLike + "%")));
//            }};
            new Grid<User>() {{
                data = new SearchBox<>(
                    new StrInput(true),
                    name -> server(db -> db.array(
                        "SELECT * FROM users WHERE name like :1",
                        User.class, "%" + name + "%")));
                columns = new Column[]{
                    new Column<User>("Id", c -> c.id),
                    new Column<User>("Имя", c -> c.name),
                    new Column<User>("Возраст", c -> c.age),
                    new Column<User>("Пол", c -> c.sex)
                };
                selectedRow = user -> {
                    var info = server(db -> db.uniqueOrNull(
                        "SELECT faculty, address, phone FROM user_info WHERE user_id = :1",
                        UserInfo.class, user.id));
                    return new div() {{
                        if (info != null) new span("Адрес: " + info.address);
                        else new span("Нет данных о студенте");
                    }};
                };
            }};
        }};
    }
}
